### PR TITLE
Merge changes from origin repo

### PR DESCRIPTION
**Pull request by sermojohn**
Changes merged from origin repo: git@github.com:sbezverk/gobmp.git

### CODE REVIEW

**Review by vkotronis — DISMISSED** [review]
LGTM

**Comment by vkotronis** [comment]
Needs conflict resolution first plus docker hub update of the 0.0.3 tag (or new 0.0.4 tag, up to you)

**Comment by sermojohn** [comment]
> Needs conflict resolution first plus docker hub update of the 0.0.3 tag (or new 0.0.4 tag, up to you)

I resolved conflicts, will make sure 0.0.3 provides the master after this PR.

**Review by vkotronis — APPROVED** [review]
LGTM

**Pull request merged**
