### PR TITLE
Upgrade v1.0.0

### PR DESCRIPTION
**Pull request by vkotronis**

### CODE REVIEW

**Comment by vkotronis** [comment]
@sermojohn this is a sync with the latest upstream `master` (I have resolved any conflicts needed), which I am testing in the other WIP in https://github.com/codebgp/bgp-data/pull/1100

**Comment by vkotronis** [comment]
Will merge if https://github.com/codebgp/bgp-data/pull/1101 passes

**Comment by vkotronis** [comment]
Will merge if https://github.com/codebgp/bgp-data/pull/1101 passes

**Comment by vkotronis** [comment]
tests pass, merging

**Comment by sermojohn** [comment]
Sorry for the late check. Hard to review here, good to see that updating with upstream was successful.

**Pull request merged**
